[project]
name = "ok-wuthering-waves"
version = "0.2.17"
description = "Automation for Wuthering Waves "
authors = ["ok-oldking <firedcto@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
python = ">=3.11"
openvino = ">=2024.3.0"

[pypi-dependencies]
rapidocr-openvino = ">=1.3.24, <2"
ok-script = ">=0.0.185"
